[package]
name = "sim-save"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
sim-app = { path = "../sim-app" }
tempfile.workspace = true
thiserror.workspace = true

[dev-dependencies]
sim-engineering = { path = "../sim-engineering" }
sim-time = { path = "../sim-time" }
sim-trajectory = { path = "../sim-trajectory" }
