[package]
name = "sim-astro"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
sim-time = { path = "../sim-time" }
thiserror.workspace = true

